// Copyright 2022 IBM Corp.
// SPDX-License-Identifier: Apache-2.0

package databasetypes

const AccessKeyID = "access_key_id"
const AdditionalProperties = "additional properties"
const AwsAccessKeyID = "awsAccessKeyId"
const AwsRegion = "awsRegion"
const AwsSecretAccessKey = "awsSecretAccessKey"
const Bucket = "bucket"
const BucketName = "bucketName"
const ConfigSource = "configSource"
const ConnectionOptions = "connectionOptions"
const CustomDatabase = "CustomDatabase"
const DatabaseSchema = "databaseSchema"
const Datalake = "Datalake"
const Default = "default"
const EmptyString = ""
const Endpoint = "endpoint"
const EndPointURL = "endPointURL"
const FailedToConvert = "%s: failed to convert interface to map"
const GetSecretFailed = "GetSecret failed"
const GetTokenFailed = "GetToken failed"
const HostPort = "hostPort"
const Mysql = "Mysql"
const ObjectKey = "object_key"
const Other = "other"
const Password = "password"
const Region = "region"
const S3 = "s3"
const Scheme = "scheme"
const SecretAccessID = "secret_access_id"
const SecurityConfig = "securityConfig"
const Type = "type"
const Username = "username"
const Value = "value"
