/*
OpenMetadata Apis

# Overview  OpenMetadata supports REST APIs for getting metadata in and out of metadata store. The API resources are grouped under following categories: - **Data assets** - includes resources for data entities, such as `databases`, `tables`, and `topics`. Resources for data assets created from data, such as `dashboards`, `reports`, `metrics`, and `ML Features` are part of this collection. `pipelines`, `notebooks`, etc. that are used for creating data assets are also available as resources as of this collection. - **Teams and Users** - includes `users`, `teams`, a special type of user called `bots` that performs many automated tasks such as ingestion. - **Services** - are services that OpenMetadata integrates with. Currently `databaseService` is the only service under this collection that represents data sources. In the future, services related to Dashboards, Reports, ETL pipelines will be added under this collection. - **Glossary** - OpenMetadata supports hierarchical tags that can be used to build business vocabulary to describe and classify data available under `tags` resource.

API version: 0.11.0
Contact: openmetadata-dev@googlegroups.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CollectionInfo struct for CollectionInfo
type CollectionInfo struct {
	Documentation *string    `json:"documentation,omitempty"`
	Href          *string    `json:"href,omitempty"`
	Images        *ImageList `json:"images,omitempty"`
	Name          *string    `json:"name,omitempty"`
}

// NewCollectionInfo instantiates a new CollectionInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCollectionInfo() *CollectionInfo {
	this := CollectionInfo{}
	return &this
}

// NewCollectionInfoWithDefaults instantiates a new CollectionInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCollectionInfoWithDefaults() *CollectionInfo {
	this := CollectionInfo{}
	return &this
}

// GetDocumentation returns the Documentation field value if set, zero value otherwise.
func (o *CollectionInfo) GetDocumentation() string {
	if o == nil || o.Documentation == nil {
		var ret string
		return ret
	}
	return *o.Documentation
}

// GetDocumentationOk returns a tuple with the Documentation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionInfo) GetDocumentationOk() (*string, bool) {
	if o == nil || o.Documentation == nil {
		return nil, false
	}
	return o.Documentation, true
}

// HasDocumentation returns a boolean if a field has been set.
func (o *CollectionInfo) HasDocumentation() bool {
	if o != nil && o.Documentation != nil {
		return true
	}

	return false
}

// SetDocumentation gets a reference to the given string and assigns it to the Documentation field.
func (o *CollectionInfo) SetDocumentation(v string) {
	o.Documentation = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *CollectionInfo) GetHref() string {
	if o == nil || o.Href == nil {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionInfo) GetHrefOk() (*string, bool) {
	if o == nil || o.Href == nil {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *CollectionInfo) HasHref() bool {
	if o != nil && o.Href != nil {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *CollectionInfo) SetHref(v string) {
	o.Href = &v
}

// GetImages returns the Images field value if set, zero value otherwise.
func (o *CollectionInfo) GetImages() ImageList {
	if o == nil || o.Images == nil {
		var ret ImageList
		return ret
	}
	return *o.Images
}

// GetImagesOk returns a tuple with the Images field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionInfo) GetImagesOk() (*ImageList, bool) {
	if o == nil || o.Images == nil {
		return nil, false
	}
	return o.Images, true
}

// HasImages returns a boolean if a field has been set.
func (o *CollectionInfo) HasImages() bool {
	if o != nil && o.Images != nil {
		return true
	}

	return false
}

// SetImages gets a reference to the given ImageList and assigns it to the Images field.
func (o *CollectionInfo) SetImages(v ImageList) {
	o.Images = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CollectionInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CollectionInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CollectionInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CollectionInfo) SetName(v string) {
	o.Name = &v
}

func (o CollectionInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Documentation != nil {
		toSerialize["documentation"] = o.Documentation
	}
	if o.Href != nil {
		toSerialize["href"] = o.Href
	}
	if o.Images != nil {
		toSerialize["images"] = o.Images
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCollectionInfo struct {
	value *CollectionInfo
	isSet bool
}

func (v NullableCollectionInfo) Get() *CollectionInfo {
	return v.value
}

func (v *NullableCollectionInfo) Set(val *CollectionInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCollectionInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCollectionInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCollectionInfo(val *CollectionInfo) *NullableCollectionInfo {
	return &NullableCollectionInfo{value: val, isSet: true}
}

func (v NullableCollectionInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCollectionInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
