package databasetypes

const AccessKeyID = "access_key_id"
const AdditionalProperties = "additional properties"
const AwsAccessKeyID = "awsAccessKeyId"
const AwsRegion = "awsRegion"
const AwsSecretAccessKey = "awsSecretAccessKey"
const Bucket = "bucket"
const BucketName = "bucketName"
const ConfigSource = "configSource"
const DatabaseSchema = "databaseSchema"
const Datalake = "Datalake"
const Default = "default"
const Endpoint = "endpoint"
const EndPointURL = "endPointURL"
const FailedToConvert = "%s: failed to convert interface to map"
const GetSecretFailed = "GetSecret failed"
const GetTokenFailed = "GetToken failed"
const Mysql = "Mysql"
const ObjectKey = "object_key"
const Other = "other"
const Region = "region"
const S3 = "s3"
const SecretAccessID = "secret_access_id"
const SecurityConfig = "securityConfig"
const Type = "type"
const Value = "value"
