name: Test

on:
  push:
    tags:
      - '*'
  pull_request:
env:
  GO_VERSION: 1.19

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
    - uses: actions/checkout@v3
    - name: autogenerate code
      run: make patch
    - name: Test
      run: make test
