/*
 * Data Catalog Service - Asset Details
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type UpdateAssetRequest struct {
	AssetID string `json:"assetID"`

	// New columns associated with the asset
	Columns []ResourceColumn `json:"columns,omitempty"`

	// New name of the resource
	Name string `json:"name,omitempty"`

	// New owner of the resource
	Owner string `json:"owner,omitempty"`

	Tags map[string]interface{} `json:"tags,omitempty"`
}

// AssertUpdateAssetRequestRequired checks if the required fields are not zero-ed
func AssertUpdateAssetRequestRequired(obj UpdateAssetRequest) error {
	elements := map[string]interface{}{
		"assetID": obj.AssetID,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Columns {
		if err := AssertResourceColumnRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertRecurseUpdateAssetRequestRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of UpdateAssetRequest (e.g. [][]UpdateAssetRequest), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseUpdateAssetRequestRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aUpdateAssetRequest, ok := obj.(UpdateAssetRequest)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertUpdateAssetRequestRequired(aUpdateAssetRequest)
	})
}
